Insert into tb_category (name)values('PC');
Insert into tb_category (name)values('TV');
Insert into tb_category (name)values('SOM');
Insert into tb_category (name)values('NOTBOOK');
Insert into tb_category (name)values('MAQUINA DE LAVAR');
Insert into tb_category (name)values('GELADEIRA');
Insert into tb_category (name)values('CAMA');
Insert into tb_category (name)values('MESA');
Insert into tb_category (name)values('SOFA');
Insert into tb_category (name)values('ARMARIO');
Insert into tb_category (name)values('FOGAO');